let cur=-1,playing=false,fav=JSON.parse(localStorage.getItem('dwp-fav')||'[]'),rec=JSON.parse(localStorage.getItem('dwp-rec')||'[]');
const C=document.getElementById('content');const esc=s=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function card(s,i){return `<article class="card"><div class="art">🎙️<button onclick="play(${i})">▶</button></div><div class="info"><b>${esc(s.title)}</b><span>${esc(s.artist)} • ${s.era}</span><div><small>${s.duration}</small><button onclick="favorite(${i})">${fav.includes(i)?'♥':'♡'}</button></div></div></article>`}
function list(arr=songs,title='Popular Songs'){C.innerHTML=`<div class="title"><h2>${title}</h2><span>${arr.length} songs</span></div><div class="grid">${arr.map(s=>card(s,songs.indexOf(s))).join('')||'<div class="empty">No songs found.</div>'}</div>`}
function home(){C.innerHTML=`<div class="title"><h2>Browse by Decade</h2></div><div class="decades">${['60s','70s','80s','90s'].map(e=>`<button class="decade" onclick="list(songs.filter(s=>s.era==='${e}'),'${e} Classics')">${e}<small>Classic melodies</small><small>Browse songs →</small></button>`).join('')}</div><div class="title"><h2>Popular Songs</h2></div><div class="grid">${songs.slice(0,6).map((s,i)=>card(s,i)).join('')}</div>`}
function allSongs(){list(songs,'All Songs')}function decades(){home()}function singers(){list(songs,'Kishore Kumar • Rafi • Lata • Mukesh • Asha')}function favorites(){list(songs.filter((_,i)=>fav.includes(i)),'My Favorites')}function recent(){list(rec.map(i=>songs[i]).filter(Boolean),'Recently Played')}function about(){C.innerHTML='<div class="empty"><h2>About दुकान वाला Playlist</h2><p>A retro music discovery website concept. Use only official, licensed, public-domain or otherwise authorized music sources when publishing.</p></div>'}
function play(i){cur=i;playing=true;let s=songs[i];document.getElementById('pt').textContent=s.title;document.getElementById('pa').textContent=s.artist;document.getElementById('now').innerHTML=`<div class="item"><div class="thumb">🎵</div><div><b>${esc(s.title)}</b><span>${esc(s.artist)}</span></div></div>`;rec=[i,...rec.filter(x=>x!==i)].slice(0,10);localStorage.setItem('dwp-rec',JSON.stringify(rec));document.querySelector('footer .play').textContent='Ⅱ';window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(s.title+' '+s.artist+' official'),'dwp_music')}
function next(){play((cur+1)%songs.length)}function prev(){play((cur-1+songs.length)%songs.length)}function toggle(){if(cur<0)play(0);else{playing=!playing;document.querySelector('footer .play').textContent=playing?'Ⅱ':'▶'}}function favorite(i){fav=fav.includes(i)?fav.filter(x=>x!==i):[...fav,i];localStorage.setItem('dwp-fav',JSON.stringify(fav));list()}
function theme(){document.body.classList.toggle('light');alert('Theme toggle demo — custom light theme can be added next.')}
function singers(){list(songs,'Singers')}
document.getElementById('search').oninput=e=>{let q=e.target.value.toLowerCase();list(songs.filter(s=>(s.title+' '+s.artist+' '+s.era).toLowerCase().includes(q)),'Search Results')}
function queue(){document.getElementById('count').textContent=songs.length;document.getElementById('queue').innerHTML=songs.map((s,i)=>`<div class="item" onclick="play(${i})"><div class="thumb">🎵</div><div><b>${esc(s.title)}</b><span>${esc(s.artist)} • ${s.duration}</span></div></div>`).join('')}
home();queue();